<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;netstandard2.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Citolab.QTI.Converter</RootNamespace>
    <PackageId>Citolab.QTI.Converter</PackageId>
    <Version>0.1.0</Version>
    <Authors>Citolab</Authors>
    <Company>Cito</Company>
    <PackageDescription>.NET QTI 2.x to QTI 3 package converter for Citolab.QTI.Uploader.</PackageDescription>
    <RepositoryUrl>https://github.com/Citolab/qti-uploader</RepositoryUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Citolab.QTI.Uploader\Citolab.QTI.Uploader.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>

