<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Citolab.QTI.Uploader\Citolab.QTI.Uploader.csproj" />
    <ProjectReference Include="..\..\src\Citolab.QTI.Converter\Citolab.QTI.Converter.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.8.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.7" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\TestData\qti2-sample.zip" Link="TestData\\qti2-sample.zip">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\TestData\qti3-sample.zip" Link="TestData\\qti3-sample.zip">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
